const express = require('express');
const cors = require('cors');
const fs = require('fs');
const { exec } = require('child_process');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.text()); // To parse text input
app.use(express.json()); // To parse JSON bodies

// PATHS (Adjust if your folder names are different)
const C_FOLDER = path.join(__dirname, '../Timetable_DSA');
const REACT_PUBLIC = path.join(__dirname, '../scheduler-frontend/public');

app.post('/api/run-engine', (req, res) => {
    console.log(">> Received Timetable Configuration...");

    // 1. Write config.txt to C Folder
    const configPath = path.join(C_FOLDER, 'config.txt');
    try {
        fs.writeFileSync(configPath, req.body);
        console.log("   [✓] Config file saved.");
    } catch (err) {
        return res.status(500).json({ error: "Failed to save config file" });
    }

    // 3. Run the C executable
    const exeName = process.platform === 'win32' ? 'timetable_system.exe' : 'timetable_system';
    const exePath = path.join(C_FOLDER, exeName);
    console.log(">> [Server] Executing C Engine...");

    // NEW: Extract locks first
    try {
        console.log(">> [Server] Extracting existing locks...");
        exec('node ../extract_locks.js', { cwd: __dirname }, (err, stdout, stderr) => {
            if (err) console.error("Lock Extraction Error:", stderr);
            else console.log(stdout);

            // Run C Engine after extraction
            exec(`"${exePath}" config.txt`, { cwd: C_FOLDER }, (error, stdout, stderr) => {
                if (error) {
                    console.error(`   [x] Exec Error: ${error.message}`);
                    // Differentiate between crash and logical failure
                    if (error.code === 1) {
                        return res.status(422).json({
                            success: false,
                            error: "Scheduling Failed: Not enough free slots or hard constraint violation."
                        });
                    }
                    return res.status(500).json({ error: "C Engine crashed", details: stderr });
                }

                console.log("   [✓] C Engine finished.");

                // 3. Move data.json to React Public Folder
                const sourceJSON = path.join(C_FOLDER, 'data.json');
                const destJSON = path.join(REACT_PUBLIC, 'data.json');

                try {
                    if (fs.existsSync(sourceJSON)) {
                        fs.copyFileSync(sourceJSON, destJSON);
                        console.log("   [✓] Synced data.json to Frontend.");
                        res.json({ success: true, message: "Timetable Updated Successfully!" });
                    } else {
                        res.status(500).json({ error: "data.json was not generated by C engine." });
                    }
                } catch (err) {
                    console.error(err);
                    res.status(500).json({ error: "Failed to move output file." });
                }
            });
        });
    } catch (e) {
        console.error("Execution failed", e);
        res.status(500).send("Execution failed");
    }
});

// NEW: Booking Endpoint
app.post('/api/book-slot', async (req, res) => {
    const { branch, sem, section, day, slot, subject, type, teacher } = req.body;
    console.log(`>> [Booking Request] ${branch} ${sem} ${section} D${day} S${slot} : ${subject} (${teacher})`);

    // 1. Ensure locks are up to date
    try {
        await new Promise((resolve, reject) => {
            exec('node ../extract_locks.js', { cwd: __dirname }, (err) => {
                if (err) reject(err); else resolve();
            });
        });
    } catch (e) {
        return res.status(500).json({ error: "Failed to sync locks." });
    }

    // 2. Run C Validation
    const exeName = process.platform === 'win32' ? 'timetable_system.exe' : 'timetable_system';
    const exePath = path.join(C_FOLDER, exeName);

    // Command: validate config.txt locked.txt <args...>
    // Note: We use existing config.txt. If that's not safe, we should save a temp one, but for now it's okay.
    const cmd = `"${exePath}" validate config.txt locked.txt "${branch}" "${sem}" "${section}" ${day} ${slot} "${subject}" "${type}" "${teacher}"`;

    exec(cmd, { cwd: C_FOLDER }, (error, stdout, stderr) => {
        if (error) {
            // Exit codes 1, 2, 3 are handled here
            if (error.code === 1) return res.status(409).json({ success: false, error: "Slot is NOT FREE." });
            if (error.code === 2) return res.status(409).json({ success: false, error: `Teacher ${teacher} is BUSY.` });
            if (error.code === 3) return res.status(400).json({ success: false, error: "Invalid Slot (Break) or Parameters." });

            console.error("Exec Error:", stderr);
            return res.status(500).json({ error: "Internal Error", details: stderr });
        }

        // 3. Success (Exit Code 0)
        // Data.json is already updated by C engine.
        // We need to sync it to React
        const sourceJSON = path.join(C_FOLDER, 'data.json');
        const destJSON = path.join(REACT_PUBLIC, 'data.json');
        fs.copyFileSync(sourceJSON, destJSON);

        res.json({ success: true, message: "Slot Booked Successfully!" });
    });
});


app.listen(5000, () => console.log("Server running on port 5000"));