const express = require('express');
const cors = require('cors');
const fs = require('fs');
const { exec } = require('child_process');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.text()); // To parse text input

// PATHS (Adjust if your folder names are different)
const C_FOLDER = path.join(__dirname, '../Timetable_DSA');
const REACT_PUBLIC = path.join(__dirname, '../scheduler-frontend/public');

app.post('/api/run-engine', (req, res) => {
    console.log(">> Received Timetable Configuration...");

    // 1. Write config.txt to C Folder
    const configPath = path.join(C_FOLDER, 'config.txt');
    try {
        fs.writeFileSync(configPath, req.body);
        console.log("   [✓] Config file saved.");
    } catch (err) {
        return res.status(500).json({ error: "Failed to save config file" });
    }

    // 2. Run the C Engine
    const exePath = path.join(C_FOLDER, 'timetable_system.exe');
    const command = `"${exePath}" config.txt`; // Pass config as argument

    console.log("   [+] Running C Engine...");
    
    // Execute command inside the C Folder (so it finds config.txt)
    exec(command, { cwd: C_FOLDER }, (error, stdout, stderr) => {
        if (error) {
            console.error(`   [x] Exec Error: ${error}`);
            return res.status(500).json({ error: "C Engine crashed", details: stderr });
        }

        console.log("   [✓] C Engine finished.");

        // 3. Move data.json to React Public Folder
        const sourceJSON = path.join(C_FOLDER, 'data.json');
        const destJSON = path.join(REACT_PUBLIC, 'data.json');

        try {
            if (fs.existsSync(sourceJSON)) {
                fs.copyFileSync(sourceJSON, destJSON);
                console.log("   [✓] Synced data.json to Frontend.");
                res.json({ success: true, message: "Timetable Updated Successfully!" });
            } else {
                res.status(500).json({ error: "data.json was not generated by C engine." });
            }
        } catch (err) {
            console.error(err);
            res.status(500).json({ error: "Failed to move output file." });
        }
    });
});

app.listen(5000, () => console.log("Server running on port 5000"));