import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { generateCInput } from '../utils/generateInputFile';
import TimetableGrid from '../components/TimetableGrid';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const Admin = () => {
  const navigate = useNavigate();

  // --- AUTHENTICATION STATE ---
  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    return sessionStorage.getItem('adminAuth') === 'true';
  });
  const [passwordInput, setPasswordInput] = useState('');
  const [authError, setAuthError] = useState(false);
  const SECRET_PASSWORD = "power!";

  // --- STATE & PERSISTENCE ---
  const [allSemesterData, setAllSemesterData] = useState(() => {
    const saved = localStorage.getItem('adminDraft');
    return saved ? JSON.parse(saved) : [];
  });

  const [showSuccess, setShowSuccess] = useState(() => {
    return localStorage.getItem('adminSuccess') === 'true';
  });

  const [step, setStep] = useState(() => {
    const success = localStorage.getItem('adminSuccess') === 'true';
    const saved = localStorage.getItem('adminDraft');
    const parsed = saved ? JSON.parse(saved) : [];
    if (success) return 3;
    if (parsed.length > 0) return 3;
    return 1;
  });

  const [editIndex, setEditIndex] = useState(null);
  const [viewAllMode, setViewAllMode] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // CHECK FOR EXISTING DATA ON MOUNT
  const [hasExistingData, setHasExistingData] = useState(false);
  useEffect(() => {
    fetch('/data.json')
      .then(res => res.json())
      .then(data => {
        if (data && data.name === "University") setHasExistingData(true);
      })
      .catch(() => setHasExistingData(false));
  }, []);

  // FORM INPUTS
  const branches = ["CS", "CY", "CI", "CD", "IS", "AS", "BT", "CH", "CV", "EC", "EE", "EI", "ET", "IM", "ME"];
  const [branch, setBranch] = useState('CS');
  const [cycle, setCycle] = useState('Odd');
  const semesterOptions = cycle === 'Odd' ? [1, 3, 5, 7] : [2, 4, 6, 8];
  const [currentSem, setCurrentSem] = useState(semesterOptions[0]);
  const [numSections, setNumSections] = useState(3);
  const [subjects, setSubjects] = useState([]);
  const [tempSubName, setTempSubName] = useState('');
  const [tempSubType, setTempSubType] = useState('Lecture');
  const [tempSubHours, setTempSubHours] = useState(4);

  useEffect(() => { setCurrentSem(cycle === 'Odd' ? 1 : 2); }, [cycle]);
  useEffect(() => {
    if (allSemesterData.length > 0) localStorage.setItem('adminDraft', JSON.stringify(allSemesterData));
  }, [allSemesterData]);

  // --- FORMAL MULTI-PAGE PDF EXPORT LOGIC ---
  // --- OPTIMIZED MULTI-PAGE PDF LOGIC ---
  const handleDownloadPDF = async () => {
    const sectionBlocks = document.querySelectorAll('.formal-pdf-page');
    if (sectionBlocks.length === 0) return alert("No timetables found.");

    setIsGenerating(true); // Show "Processing..."

    try {
      const pdf = new jsPDF('l', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const contentWidth = pdfWidth - (margin * 2);

      for (let i = 0; i < sectionBlocks.length; i++) {
        const block = sectionBlocks[i];

        // Optimization: Use a smaller scale if it's hanging, or wait for the DOM
        const canvas = await html2canvas(block, {
          scale: 1.5, // Reduced slightly for faster processing
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
          removeContainer: true // Helps with memory cleanup
        });

        const imgData = canvas.toDataURL('image/png', 0.8); // 0.8 compression helps speed
        const imgHeight = (canvas.height * contentWidth) / canvas.width;

        // Formal Header
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(20);
        pdf.setTextColor(30, 41, 59);
        pdf.text("OFFICIAL ACADEMIC TIMETABLE", pdfWidth / 2, 18, { align: "center" });

        pdf.setFontSize(12);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Department of ${branch} Engineering | Session 2025-26`, pdfWidth / 2, 25, { align: "center" });

        pdf.setDrawColor(200);
        pdf.line(margin, 28, pdfWidth - margin, 28);

        pdf.addImage(imgData, 'PNG', margin, 32, contentWidth, imgHeight);

        // Footer
        pdf.setFontSize(10);
        pdf.setTextColor(100);
        pdf.text("Generated by Scheduling System", margin, pdfHeight - 10);


        if (i < sectionBlocks.length - 1) {
          pdf.addPage();
        }

        // CRITICAL: Small delay to prevent browser freeze
        await new Promise(resolve => setTimeout(resolve, 200));
      }

      pdf.save(`${branch}_Timetables.pdf`);
    } catch (error) {
      console.error("PDF Error:", error);
      alert("Error generating PDF. Try reducing the number of sections.");
    } finally {
      setIsGenerating(false); // Reset button state
    }
  };

  // --- STYLES (Responsive) ---
  const pageStyle = {
    minHeight: '100vh', width: '100vw', display: 'flex', flexDirection: 'column',
    alignItems: 'center', background: 'linear-gradient(135deg, #020617 0%, #0f172a 60%, #1e293b 100%)',
    color: 'white', overflowX: 'hidden', overflowY: 'auto', fontFamily: "'Inter', sans-serif", padding: 'clamp(15px, 3vw, 30px)'
  };

  const glassContainerStyle = {
    flex: 1, width: '100%', maxWidth: '1800px', background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.12)', backdropFilter: 'blur(25px)',
    borderRadius: 'clamp(20px, 3vw, 40px)', padding: 'clamp(20px, 3vw, 40px) clamp(15px, 4vw, 60px)', boxShadow: '0 30px 80px rgba(0,0,0,0.6)',
    display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative'
  };

  const bigInputStyle = {
    width: '100%', padding: 'clamp(12px, 2vw, 25px) clamp(15px, 2vw, 30px)', fontSize: 'clamp(1rem, 1.8vw, 1.6rem)', background: '#1e293b',
    border: '2px solid rgba(255, 255, 255, 0.2)', borderRadius: 'clamp(12px, 2vw, 20px)', color: 'white',
    outline: 'none', transition: 'border-color 0.2s', fontFamily: 'inherit', boxSizing: 'border-box'
  };

  const largeBtnStyle = {
    padding: 'clamp(12px, 2vw, 22px) clamp(20px, 3vw, 50px)', fontSize: 'clamp(0.9rem, 1.8vw, 1.6rem)', borderRadius: 'clamp(12px, 2vw, 20px)', border: 'none',
    cursor: 'pointer', fontWeight: '700', transition: 'all 0.2s', display: 'inline-flex',
    alignItems: 'center', gap: '10px'
  };

  // --- AUTH LOGIC ---
  const handleLogin = (e) => {
    e.preventDefault();
    if (passwordInput === SECRET_PASSWORD) {
      setIsAuthenticated(true);
      sessionStorage.setItem('adminAuth', 'true');
      setAuthError(false);
    } else { setAuthError(true); }
  };

  // --- LOGIC ---
  const handleCreateSubject = () => {
    if (!tempSubName) return alert("Enter Subject Name");
    setSubjects([...subjects, { id: Date.now(), name: tempSubName, type: tempSubType, hours: parseInt(tempSubHours), teachers: [] }]);
    setTempSubName('');
  };

  const handleAddTeacherToSubject = (idx) => {
    const val = document.getElementById(`t-input-${idx}`).value;
    if (!val) return;
    const upd = [...subjects]; upd[idx].teachers.push(val); setSubjects(upd);
    document.getElementById(`t-input-${idx}`).value = '';
  };

  const handleSaveSemester = () => {
    if (subjects.length === 0) return alert("Add at least one subject!");
    const invalid = subjects.find(s => s.teachers.length === 0);
    if (invalid) return alert(`Assign a teacher to ${invalid.name}`);
    const newSem = { branch, cycle, semester: currentSem, sections: numSections, courses: subjects };
    if (editIndex !== null) { const d = [...allSemesterData]; d[editIndex] = newSem; setAllSemesterData(d); setEditIndex(null); }
    else { setAllSemesterData([...allSemesterData, newSem]); }
    setSubjects([]); setStep(3);
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    const content = generateCInput(allSemesterData, branch);
    try {
      const response = await fetch('/api/run-engine', {
        method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: content
      });
      const result = await response.json();
      if (result.success) {
        setShowSuccess(true);
        localStorage.setItem('adminSuccess', 'true');
      } else { alert("Error: " + result.error); }
    } catch (err) { alert("Connection Error: Engine server not responding."); } finally { setIsGenerating(false); }
  };

  const handleClearAll = async () => {
    if (!window.confirm("Are you sure? This will DELETE the entire schedule from the server.")) return;

    try {
      await fetch('/api/system-reset', { method: 'DELETE' });
    } catch (e) { console.error("Reset failed", e); }

    localStorage.removeItem('adminDraft'); localStorage.removeItem('adminSuccess');
    setAllSemesterData([]); setShowSuccess(false); setStep(1); setViewAllMode(false);
    setHasExistingData(false);
  };

  const reconstructAndLoad = (mode = 'VIEW') => {
    fetch('/data.json')
      .then(res => res.json())
      .then(data => {
        if (!data || !data.children) return alert("Invalid Data Format");

        const reconstructed = [];
        data.children.forEach(branchNode => {
          if (branchNode.type !== 1) return;
          const branchName = branchNode.name;
          branchNode.children.forEach(semNode => {
            if (semNode.type !== 2) return;
            const semName = semNode.name; // "Semester_1"
            const semesterNum = parseInt(semName.split('_')[1]);
            const sectionCount = semNode.children ? semNode.children.length : 0;

            // Extract courses from grid cells of the FIRST section
            // Format: "SubjectName (Type)\nTeacherName"
            const courseMap = {}; // key: "SubjectName|Type" -> { name, type, hours, teachers: Set }
            const firstSection = semNode.children && semNode.children[0];
            if (firstSection && firstSection.grid) {
              firstSection.grid.forEach(row => {
                row.forEach(cell => {
                  if (!cell || cell === "FREE" || cell === "BREAK" || cell === "LUNCH" || cell === "-") return;
                  // Parse "SubjectName (Type)\nTeacherName"
                  const parts = cell.split('\n');
                  if (parts.length < 2) return;
                  const match = parts[0].match(/^(.+?)\s*\((\w+)\)$/);
                  if (!match) return;
                  const subName = match[1].trim();
                  const subType = match[2].trim();
                  const teacher = parts[1].trim();
                  const key = `${subName}|${subType}`;
                  if (!courseMap[key]) {
                    courseMap[key] = { name: subName, type: subType, hours: 0, teachers: new Set() };
                  }
                  courseMap[key].hours++;
                  courseMap[key].teachers.add(teacher);
                });
              });
            }

            const courses = Object.values(courseMap).map(c => ({
              id: Date.now() + Math.random(),
              name: c.name,
              type: c.type,
              hours: c.hours || 4,
              teachers: Array.from(c.teachers)
            }));

            reconstructed.push({
              branch: branchName,
              semester: semesterNum,
              sections: sectionCount,
              cycle: semesterNum % 2 !== 0 ? 'Odd' : 'Even',
              courses
            });
          });
        });

        if (reconstructed.length === 0) return alert("No schedule data found on server.");

        setAllSemesterData(reconstructed);
        localStorage.setItem('adminDraft', JSON.stringify(reconstructed));

        if (mode === 'EDIT') {
          setStep(3);
          setViewAllMode(false);
          setShowSuccess(false);
        } else {
          setViewAllMode(true);
        }
      })
      .catch(err => alert("Failed to load data: " + err));
  };

  const handleViewMaster = () => {
    if (allSemesterData.length > 0) {
      setViewAllMode(true);
    } else {
      reconstructAndLoad('VIEW');
    }
  };

  const handleContinue = () => {
    if (allSemesterData.length > 0) {
      setStep(3);
      setViewAllMode(false);
      setShowSuccess(false);
    } else {
      reconstructAndLoad('EDIT');
    }
  };

  if (!isAuthenticated) {
    return (
      <div style={{ ...pageStyle, justifyContent: 'center' }}>
        <div className="glass-container" style={{ ...glassContainerStyle, maxWidth: 'min(90vw, 700px)', minHeight: '400px', flex: 'none', justifyContent: 'center', alignItems: 'center' }}>
          <div style={{ fontSize: 'clamp(3.5rem, 6vw, 7rem)', marginBottom: '20px' }}>🔐</div>
          <h1 style={{ fontSize: 'clamp(2rem, 4vw, 4rem)', fontWeight: '900', marginBottom: '15px', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Admin Access</h1>
          <form onSubmit={handleLogin} style={{ width: '100%' }}>
            <input type="password" placeholder="Password" autoFocus style={{ ...bigInputStyle, textAlign: 'center', fontSize: 'clamp(1.2rem, 2vw, 2rem)', borderColor: authError ? '#ef4444' : 'rgba(255,255,255,0.2)' }} value={passwordInput} onChange={(e) => setPasswordInput(e.target.value)} />
            {authError && <p style={{ color: '#ef4444', marginTop: '15px', fontWeight: 'bold' }}>Invalid Credentials</p>}
            <div className="btn-group" style={{ marginTop: '30px', display: 'flex', gap: '20px', justifyContent: 'center' }}>
              <button type="button" style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: 'white' }} onClick={() => navigate('/')}>Cancel</button>
              <button type="submit" style={{ ...largeBtnStyle, background: '#3b82f6', color: 'white' }}>Login</button>
            </div>
          </form>
        </div>
      </div>
    );
  }

  if (viewAllMode) {
    return (
      <div style={pageStyle}>
        <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%', maxWidth: '1800px', marginBottom: 'clamp(15px, 2vw, 30px)' }}>
          <h1 style={{ fontSize: 'clamp(1.8rem, 5vw, 5rem)', fontWeight: '900', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Master Schedule</h1>
          <div className="btn-group" style={{ display: 'flex', gap: '15px', flexWrap: 'wrap' }}>
            <button style={{ ...largeBtnStyle, background: '#10b981', color: 'white' }} onClick={handleDownloadPDF} disabled={isGenerating}>
              {isGenerating ? "Processing..." : "📥 PDF"}
            </button>
            <button style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: 'white' }} onClick={() => setViewAllMode(false)}>← Back</button>
          </div>
        </div>
        <div style={glassContainerStyle}>
          <div style={{ overflowY: 'auto', height: '100%', paddingRight: '20px' }}>
            {/* IF NO DRAFT DATA, BUT WE HAVE SERVER DATA, WE SHOULD FETCH & DISPLAY THE SERVER DATA INSTEAD OF EMPTY DRAFT */}
            {(allSemesterData.length > 0 ? allSemesterData : [{ branch: 'View', semester: 'Master', sections: 1 }]).map((sem, i) => (
              <div key={i}>
                {/* 
                    HACK FOR MVP: If 'allSemesterData' is empty (cleared) but 'hasExistingData' is true, 
                    TimetableGrid will fetch 'data.json' internally anyway.
                    We just need to render *something* to trigger TimetableGrid.
                    However, TimetableGrid needs Branch/Sem/Sec to navigate the tree.
                    If we don't have that metadata in 'allSemesterData', we can't easily auto-generate the view 
                    unless we parse data.json here.
                    
                    Better approach: Just let TimetableGrid handle it? 
                    Actually, TimetableGrid takes props `branch`, `semester`, `section`. 
                    If we don't know them (because we cleared local storage), we might not be able to render specific sections.
                    
                    WAIT: The user wants to "VIEW MASTER DATA". TimetableGrid component logic is:
                    fetch data.json -> traverse tree.
                    
                    If we want to display the *entire* schedule, we need to know the structure (Branches, Sems, Sections).
                    That structure is usually in `allSemesterData`.
                    If the user CLEARED local storage, we lost the structure map.
                    
                    Options:
                    1. Re-construct structure from data.json (harder).
                    2. Just show a "Search/Explorer" view instead of iterating sections?
                    3. Assume simple defaults or fetch structure from server?
                    
                    Let's assume for now the user hasn't cleared the *backend* json, avoiding complexity.
                    But if they cleared *local* storage, `allSemesterData` is empty.
                    
                    Let's update logic: 
                    If master data exists, provide a button that opens a "School Explorer" or uses `generateCInput` logic?
                    
                    Actually, `TimetableGrid` is designed to show a specific section.
                    
                    Let's try to just read the `data.json` structure in the `useEffect` and populate `allSemesterData` if it's empty?
                    That would be robust.
                */}
                {allSemesterData.length > 0 ? (
                  Array.from({ length: sem.sections }).map((_, secIdx) => {
                    const secLetter = String.fromCharCode(65 + secIdx);
                    return (
                      <div key={secLetter} className="formal-pdf-page" style={{ height: 'auto', minHeight: '70vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', borderBottom: '2px dashed rgba(255,255,255,0.1)', marginBottom: 'clamp(40px, 7vw, 100px)', paddingBottom: 'clamp(20px, 4vw, 60px)', background: 'transparent' }}>
                        <div style={{ marginBottom: 'clamp(15px, 2vw, 30px)' }}>
                          <span style={{ fontSize: 'clamp(1.2rem, 2.5vw, 2.2rem)', color: '#94a3b8', display: 'block', marginBottom: '8px' }}>{sem.branch} • Semester {sem.semester}</span>
                          <h3 style={{ fontSize: 'clamp(2rem, 4.5vw, 4.5rem)', color: '#60a5fa', margin: 0 }}>Section {secLetter}</h3>
                        </div>
                        <div style={{ width: '100%', overflowX: 'auto' }}>
                          <TimetableGrid role="STUDENT" branch={sem.branch} semester={sem.semester} section={`Sec_${secLetter}`} key={Date.now()} />
                        </div>
                      </div>
                    );
                  })
                ) : (
                  <div style={{ textAlign: 'center', marginTop: '50px' }}>
                    <h2>Metadata missing from local storage.</h2>
                    <p>Showing raw data unavailable without structure.</p>
                    {/* 
                           We can implement a quick 'Restore' here if needed, 
                           but for now let's focus on the Buttons in Step 1.
                        */}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  // --- RECONSTRUCT DATA FROM JSON FUNCTION ---
  // (We'll implement this properly later if needed, for now focus on the UI buttons)

  return (
    <div style={pageStyle}>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%', maxWidth: '1800px', marginBottom: 'clamp(15px, 2vw, 30px)' }}>
        <h1 style={{ fontSize: 'clamp(1.8rem, 5vw, 5rem)', fontWeight: '900', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Admin Portal</h1>
        <button style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: '#cbd5f5' }} onClick={() => navigate('/')}>🏠 Home</button>
      </div>



      <div className="glass-container" style={glassContainerStyle}>

        {/* DASHBOARD HEADER IF DATA EXISTS */}
        {hasExistingData && step === 1 && (
          <div className="existing-data-banner" style={{ marginBottom: 'clamp(20px, 3vw, 40px)', padding: 'clamp(15px, 2vw, 30px)', background: 'rgba(16, 185, 129, 0.1)', borderRadius: 'clamp(15px, 2vw, 25px)', border: '1px solid rgba(16, 185, 129, 0.3)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <h2 style={{ fontSize: 'clamp(1.3rem, 2.5vw, 2.5rem)', color: '#34d399', margin: 0 }}>📅 Existing Schedule Found</h2>
              <p style={{ color: '#ecfdf5', fontSize: 'clamp(0.8rem, 1.3vw, 1.2rem)', margin: '5px 0 0 0' }}>Master Timetable is active.</p>
            </div>
            <div className="btn-group" style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
              <button onClick={handleContinue} style={{ ...largeBtnStyle, background: '#3b82f6', color: 'white' }}>
                ✏️ Continue
              </button>
              <button onClick={handleViewMaster} style={{ ...largeBtnStyle, background: '#10b981', color: 'white' }}>
                👁 View
              </button>
              <button onClick={handleClearAll} style={{ ...largeBtnStyle, background: '#ef4444', color: 'white' }}>
                🗑 Clear
              </button>
            </div>
          </div>
        )}

        {step === 1 && (
          <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: '10px' }}>
              <h2 style={{ fontSize: 'clamp(1.5rem, 3vw, 3rem)', marginBottom: 'clamp(20px, 3vw, 40px)' }}>Step 1: Academy Configuration</h2>
              {!hasExistingData && allSemesterData.length > 0 &&
                <button onClick={handleClearAll} style={{ ...largeBtnStyle, background: 'rgba(239, 68, 68, 0.2)', color: '#fca5a5', height: 'fit-content' }}>Reset Draft</button>
              }
            </div>
            <div className="form-grid-2col" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'clamp(20px, 4vw, 60px)' }}>
              <div><label style={{ fontSize: 'clamp(1rem, 2vw, 1.8rem)', color: '#cbd5f5', display: 'block', marginBottom: '10px' }}>Branch</label><select value={branch} onChange={e => setBranch(e.target.value)} style={bigInputStyle}>{branches.map(b => <option key={b} value={b}>{b}</option>)}</select></div>
              <div><label style={{ fontSize: 'clamp(1rem, 2vw, 1.8rem)', color: '#cbd5f5', display: 'block', marginBottom: '10px' }}>Cycle</label><select value={cycle} onChange={e => setCycle(e.target.value)} style={bigInputStyle}><option value="Odd">Odd (Sem 1,3,5,7)</option><option value="Even">Even (Sem 2,4,6,8)</option></select></div>
              <div><label style={{ fontSize: 'clamp(1rem, 2vw, 1.8rem)', color: '#cbd5f5', display: 'block', marginBottom: '10px' }}>Semester</label><select value={currentSem} onChange={e => setCurrentSem(parseInt(e.target.value))} style={bigInputStyle}>{semesterOptions.map(s => <option key={s} value={s}>Sem {s}</option>)}</select></div>
              <div><label style={{ fontSize: 'clamp(1rem, 2vw, 1.8rem)', color: '#cbd5f5', display: 'block', marginBottom: '10px' }}>Sections</label><select value={numSections} onChange={e => setNumSections(parseInt(e.target.value))} style={bigInputStyle}>{[1, 2, 3, 4, 5, 6].map(n => <option key={n} value={n}>{n} Sections</option>)}</select></div>
            </div>
            <div style={{ marginTop: 'auto', display: 'flex', justifyContent: 'flex-end', paddingTop: '20px' }}><button style={{ ...largeBtnStyle, background: '#3b82f6', color: 'white' }} onClick={() => setStep(2)}>Next Step →</button></div>
          </div>
        )}

        {step === 2 && (
          <div style={{ height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <h2 style={{ fontSize: 'clamp(1.5rem, 3vw, 3rem)', marginBottom: 'clamp(15px, 2vw, 30px)' }}>Step 2: Curriculum (Sem {currentSem})</h2>
            <div style={{ background: 'rgba(0,0,0,0.2)', padding: 'clamp(12px, 2vw, 20px)', borderRadius: 'clamp(12px, 2vw, 20px)', marginBottom: '15px' }}>
              <div className="form-grid-2col" style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr auto', gap: 'clamp(10px, 1.5vw, 20px)', alignItems: 'end' }}>
                <div><label style={{ color: '#cbd5f5', display: 'block', marginBottom: '6px', fontSize: 'clamp(0.8rem, 1.2vw, 1rem)' }}>Subject Name</label><input style={{ ...bigInputStyle, padding: '10px', fontSize: 'clamp(0.9rem, 1.3vw, 1.1rem)' }} value={tempSubName} onChange={e => setTempSubName(e.target.value)} /></div>
                <div><label style={{ color: '#cbd5f5', display: 'block', marginBottom: '6px', fontSize: 'clamp(0.8rem, 1.2vw, 1rem)' }}>Type</label><select style={{ ...bigInputStyle, padding: '10px', fontSize: 'clamp(0.9rem, 1.3vw, 1.1rem)' }} value={tempSubType} onChange={e => setTempSubType(e.target.value)}><option value="Lecture">Lecture</option><option value="Lab">Lab</option></select></div>
                <div><label style={{ color: '#cbd5f5', display: 'block', marginBottom: '6px', fontSize: 'clamp(0.8rem, 1.2vw, 1rem)' }}>Hrs</label><input style={{ ...bigInputStyle, padding: '10px', fontSize: 'clamp(0.9rem, 1.3vw, 1.1rem)' }} type="number" value={tempSubHours} onChange={e => setTempSubHours(e.target.value)} /></div>
                <button style={{ ...largeBtnStyle, background: '#10b981', color: 'white', height: '46px', padding: '0 15px', display: 'flex', justifyContent: 'center' }} onClick={handleCreateSubject}>Add</button>
              </div>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {subjects.map((sub, idx) => (
                <div key={idx} style={{ background: 'rgba(255,255,255,0.05)', padding: 'clamp(10px, 1.5vw, 15px) clamp(12px, 2vw, 25px)', borderRadius: 'clamp(10px, 1.5vw, 15px)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', flexWrap: 'wrap' }}>
                    <strong style={{ fontSize: 'clamp(1rem, 2vw, 1.8rem)' }}>
                      {sub.name}, {sub.type}
                      {sub.teachers.length > 0 && <span style={{ fontSize: 'clamp(0.85rem, 1.5vw, 1.4rem)', fontWeight: '400', color: '#cbd5f5', marginLeft: '8px' }}>({sub.teachers.join(', ')})</span>}
                    </strong>
                    <button onClick={() => { const u = subjects.filter((_, i) => i !== idx); setSubjects(u) }} style={{ color: '#ef4444', background: 'none', border: 'none', cursor: 'pointer', fontSize: 'clamp(0.85rem, 1.2vw, 1.1rem)' }}>Remove</button>
                  </div>
                  <div style={{ display: 'flex', gap: '10px' }}>
                    <input id={`t-input-${idx}`} placeholder="Add Teacher..." style={{ ...bigInputStyle, padding: '8px', fontSize: 'clamp(0.85rem, 1.2vw, 1rem)', flex: 1 }} />
                    <button style={{ ...largeBtnStyle, padding: '8px 16px', height: '40px' }} onClick={() => handleAddTeacherToSubject(idx)}>+</button>
                  </div>
                </div>
              ))}
            </div>
            <div style={{ marginTop: '30px', display: 'flex', justifyContent: 'space-between' }}><button style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)' }} onClick={() => setStep(1)}>Back</button><button style={{ ...largeBtnStyle, background: '#3b82f6', color: 'white' }} onClick={handleSaveSemester}>Save Semester</button></div>
          </div>
        )}

        {step === 3 && !showSuccess && (
          <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 'clamp(20px, 3vw, 40px)', flexWrap: 'wrap', gap: '10px' }}><h2 style={{ fontSize: 'clamp(1.5rem, 3vw, 3rem)' }}>Draft Dashboard</h2><button onClick={handleClearAll} style={{ ...largeBtnStyle, background: '#ef4444', color: 'white' }}>Clear All</button></div>
            <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 'clamp(15px, 2vw, 30px)' }}>
              {allSemesterData.map((sem, idx) => (
                <div className="draft-card" key={idx} style={{ background: 'rgba(255,255,255,0.05)', padding: 'clamp(18px, 3vw, 35px)', borderRadius: 'clamp(15px, 2vw, 25px)', cursor: 'pointer' }} onClick={() => { setEditIndex(idx); setBranch(sem.branch); setCurrentSem(sem.semester); setNumSections(sem.sections); setSubjects(sem.courses); setStep(2); }}>
                  <strong style={{ fontSize: 'clamp(1.3rem, 2.5vw, 2.5rem)' }}>{sem.branch} - Sem {sem.semester}</strong>
                  <p style={{ color: '#94a3b8', fontSize: 'clamp(0.85rem, 1.3vw, 1rem)' }}>{sem.sections} Sections • {sem.courses.length} Subjects</p>
                </div>
              ))}
            </div>
            <div className="btn-group" style={{ marginTop: '30px', display: 'flex', gap: 'clamp(15px, 2vw, 30px)' }}><button style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)', flex: 1 }} onClick={() => setStep(1)}>+ Add Semester</button><button style={{ ...largeBtnStyle, background: '#10b981', color: 'white', flex: 2, justifyContent: 'center' }} onClick={handleGenerate} disabled={isGenerating}>{isGenerating ? "Generating..." : "🚀 Generate All"}</button></div>
          </div>
        )}

        {step === 3 && showSuccess && (
          <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{ fontSize: 'clamp(3rem, 5vw, 6rem)', marginBottom: '20px' }}>🎉</div>
            <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3.5rem)', marginBottom: '15px', background: 'linear-gradient(to right, #34d399, #10b981)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', textAlign: 'center' }}>Timetable Generated!</h2>
            <p style={{ fontSize: 'clamp(0.9rem, 1.5vw, 1.4rem)', color: '#cbd5f5', marginBottom: 'clamp(25px, 4vw, 50px)', textAlign: 'center' }}>The optimization engine has successfully created the schedule.</p>
            <div className="btn-group" style={{ display: 'flex', gap: 'clamp(15px, 2vw, 30px)', flexWrap: 'wrap', justifyContent: 'center' }}>
              <button onClick={handleContinue} style={{ ...largeBtnStyle, background: '#3b82f6', color: 'white' }}>✏️ Continue</button>
              <button onClick={() => setViewAllMode(true)} style={{ ...largeBtnStyle, background: '#10b981', color: 'white' }}>👁 View Schedule</button>
              <button onClick={handleClearAll} style={{ ...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: 'white' }}>Start New</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Admin;