import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { generateCInput } from '../utils/generateInputFile';
import TimetableGrid from '../components/TimetableGrid';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const Admin = () => {
  const navigate = useNavigate();

  // --- AUTHENTICATION STATE ---
  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    return sessionStorage.getItem('adminAuth') === 'true';
  });
  const [passwordInput, setPasswordInput] = useState('');
  const [authError, setAuthError] = useState(false);
  const SECRET_PASSWORD = "power!"; 

  // --- STATE & PERSISTENCE ---
  const [allSemesterData, setAllSemesterData] = useState(() => {
    const saved = localStorage.getItem('adminDraft');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [showSuccess, setShowSuccess] = useState(() => {
    return localStorage.getItem('adminSuccess') === 'true';
  });

  const [step, setStep] = useState(() => {
    const success = localStorage.getItem('adminSuccess') === 'true';
    const saved = localStorage.getItem('adminDraft');
    const parsed = saved ? JSON.parse(saved) : [];
    if (success) return 3; 
    if (parsed.length > 0) return 3;
    return 1;
  });

  const [editIndex, setEditIndex] = useState(null);
  const [viewAllMode, setViewAllMode] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false); 

  // FORM INPUTS
  const branches = ["CS", "CY", "CI", "CD", "IS", "AS", "BT", "CH", "CV", "EC", "EE", "EI", "ET", "IM", "ME"];
  const [branch, setBranch] = useState('CS');
  const [cycle, setCycle] = useState('Odd');
  const semesterOptions = cycle === 'Odd' ? [1, 3, 5, 7] : [2, 4, 6, 8];
  const [currentSem, setCurrentSem] = useState(semesterOptions[0]);
  const [numSections, setNumSections] = useState(3);
  const [subjects, setSubjects] = useState([]);
  const [tempSubName, setTempSubName] = useState('');
  const [tempSubType, setTempSubType] = useState('Lecture');
  const [tempSubHours, setTempSubHours] = useState(4);

  useEffect(() => { setCurrentSem(cycle === 'Odd' ? 1 : 2); }, [cycle]);
  useEffect(() => { 
      if (allSemesterData.length > 0) localStorage.setItem('adminDraft', JSON.stringify(allSemesterData));
  }, [allSemesterData]);

  // --- FORMAL MULTI-PAGE PDF EXPORT LOGIC ---
  // --- OPTIMIZED MULTI-PAGE PDF LOGIC ---
  const handleDownloadPDF = async () => {
    const sectionBlocks = document.querySelectorAll('.formal-pdf-page');
    if (sectionBlocks.length === 0) return alert("No timetables found.");

    setIsGenerating(true); // Show "Processing..."

    try {
      const pdf = new jsPDF('l', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const contentWidth = pdfWidth - (margin * 2);

      for (let i = 0; i < sectionBlocks.length; i++) {
        const block = sectionBlocks[i];
        
        // Optimization: Use a smaller scale if it's hanging, or wait for the DOM
        const canvas = await html2canvas(block, {
          scale: 1.5, // Reduced slightly for faster processing
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
          removeContainer: true // Helps with memory cleanup
        });

        const imgData = canvas.toDataURL('image/png', 0.8); // 0.8 compression helps speed
        const imgHeight = (canvas.height * contentWidth) / canvas.width;

        // Formal Header
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(20);
        pdf.setTextColor(30, 41, 59);
        pdf.text("OFFICIAL ACADEMIC TIMETABLE", pdfWidth / 2, 18, { align: "center" });
        
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Department of ${branch} Engineering | Session 2025-26`, pdfWidth / 2, 25, { align: "center" });
        
        pdf.setDrawColor(200);
        pdf.line(margin, 28, pdfWidth - margin, 28);

        pdf.addImage(imgData, 'PNG', margin, 32, contentWidth, imgHeight);

        // Footer
        pdf.setFontSize(10);
        pdf.setTextColor(100);
        pdf.text("Generated by Scheduling System", margin, pdfHeight - 10);
       

        if (i < sectionBlocks.length - 1) {
          pdf.addPage();
        }

        // CRITICAL: Small delay to prevent browser freeze
        await new Promise(resolve => setTimeout(resolve, 200));
      }

      pdf.save(`${branch}_Timetables.pdf`);
    } catch (error) {
      console.error("PDF Error:", error);
      alert("Error generating PDF. Try reducing the number of sections.");
    } finally {
      setIsGenerating(false); // Reset button state
    }
  };

  // --- STYLES ---
  const pageStyle = {
    height: '100vh', width: '100vw', display: 'flex', flexDirection: 'column',
    alignItems: 'center', background: 'linear-gradient(135deg, #020617 0%, #0f172a 60%, #1e293b 100%)',
    color: 'white', overflow: 'hidden', fontFamily: "'Inter', sans-serif", padding: '30px' 
  };

  const glassContainerStyle = {
    flex: 1, width: '100%', maxWidth: '1800px', background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.12)', backdropFilter: 'blur(25px)',
    borderRadius: '40px', padding: '40px 60px', boxShadow: '0 30px 80px rgba(0,0,0,0.6)',
    display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative'
  };

  const bigInputStyle = {
    width: '100%', padding: '25px 30px', fontSize: '1.6rem', background: '#1e293b', 
    border: '2px solid rgba(255, 255, 255, 0.2)', borderRadius: '20px', color: 'white',
    outline: 'none', transition: 'border-color 0.2s', fontFamily: 'inherit'
  };

  const largeBtnStyle = {
    padding: '22px 50px', fontSize: '1.6rem', borderRadius: '20px', border: 'none',
    cursor: 'pointer', fontWeight: '700', transition: 'all 0.2s', display: 'inline-flex',
    alignItems: 'center', gap: '15px'
  };

  // --- AUTH LOGIC ---
  const handleLogin = (e) => {
    e.preventDefault();
    if (passwordInput === SECRET_PASSWORD) {
      setIsAuthenticated(true);
      sessionStorage.setItem('adminAuth', 'true');
      setAuthError(false);
    } else { setAuthError(true); }
  };

  // --- LOGIC ---
  const handleCreateSubject = () => {
    if (!tempSubName) return alert("Enter Subject Name");
    setSubjects([...subjects, { id: Date.now(), name: tempSubName, type: tempSubType, hours: parseInt(tempSubHours), teachers: [] }]);
    setTempSubName('');
  };

  const handleAddTeacherToSubject = (idx) => {
    const val = document.getElementById(`t-input-${idx}`).value;
    if (!val) return;
    const upd = [...subjects]; upd[idx].teachers.push(val); setSubjects(upd);
    document.getElementById(`t-input-${idx}`).value = ''; 
  };

  const handleSaveSemester = () => {
    if (subjects.length === 0) return alert("Add at least one subject!");
    const invalid = subjects.find(s => s.teachers.length === 0);
    if (invalid) return alert(`Assign a teacher to ${invalid.name}`);
    const newSem = { branch, cycle, semester: currentSem, sections: numSections, courses: subjects };
    if (editIndex !== null) { const d = [...allSemesterData]; d[editIndex] = newSem; setAllSemesterData(d); setEditIndex(null); } 
    else { setAllSemesterData([...allSemesterData, newSem]); }
    setSubjects([]); setStep(3);
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    const content = generateCInput(allSemesterData, branch);
    try {
        const response = await fetch('http://localhost:5000/api/run-engine', {
            method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: content
        });
        const result = await response.json();
        if (result.success) {
            setShowSuccess(true);
            localStorage.setItem('adminSuccess', 'true');
        } else { alert("Error: " + result.error); }
    } catch (err) { alert("Connection Error: Engine server not responding."); } finally { setIsGenerating(false); }
  };

  const handleClearAll = () => {
      localStorage.removeItem('adminDraft'); localStorage.removeItem('adminSuccess');
      setAllSemesterData([]); setShowSuccess(false); setStep(1);
  };

  if (!isAuthenticated) {
    return (
      <div style={{...pageStyle, justifyContent: 'center'}}>
        <div style={{...glassContainerStyle, maxWidth: '700px', height: '600px', flex: 'none', justifyContent: 'center', alignItems: 'center'}}>
           <div style={{fontSize: '7rem', marginBottom: '30px'}}>🔐</div>
           <h1 style={{fontSize: '4rem', fontWeight: '900', marginBottom: '15px', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'}}>Admin Access</h1>
           <form onSubmit={handleLogin} style={{width: '100%'}}>
              <input type="password" placeholder="Password" autoFocus style={{...bigInputStyle, textAlign: 'center', fontSize: '2rem', borderColor: authError ? '#ef4444' : 'rgba(255,255,255,0.2)'}} value={passwordInput} onChange={(e) => setPasswordInput(e.target.value)} />
              {authError && <p style={{color: '#ef4444', marginTop: '15px', fontWeight: 'bold'}}>Invalid Credentials</p>}
              <div style={{marginTop: '40px', display: 'flex', gap: '25px', justifyContent: 'center'}}>
                <button type="button" style={{...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: 'white'}} onClick={() => navigate('/')}>Cancel</button>
                <button type="submit" style={{...largeBtnStyle, background: '#3b82f6', color: 'white'}}>Login</button>
              </div>
           </form>
        </div>
      </div>
    );
  }

  if (viewAllMode) {
      return (
          <div style={pageStyle}>
              <div style={{display:'flex', justifyContent:'space-between', alignItems:'center', width:'100%', maxWidth:'1800px', marginBottom:'30px'}}>
                  <h1 style={{fontSize: '5rem', fontWeight:'900', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'}}>Master Schedule</h1>
                  <div style={{display:'flex', gap:'20px'}}>
                      <button style={{...largeBtnStyle, background:'#10b981', color:'white'}} onClick={handleDownloadPDF} disabled={isGenerating}>
                        {isGenerating ? "Processing..." : "📥 Download Formal PDF"}
                      </button>
                      <button style={{...largeBtnStyle, background:'rgba(255,255,255,0.1)', color:'white'}} onClick={() => setViewAllMode(false)}>← Back</button>
                  </div>
              </div>
              <div style={glassContainerStyle}>
                  <div style={{overflowY:'auto', height:'100%', paddingRight:'20px'}}>
                      {allSemesterData.map((sem, i) => (
                          <div key={i}>
                              {Array.from({length: sem.sections}).map((_, secIdx) => {
                                  const secLetter = String.fromCharCode(65 + secIdx);
                                  return (
                                      <div key={secLetter} className="formal-pdf-page" style={{ height: 'auto', minHeight: '85vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', borderBottom: '2px dashed rgba(255,255,255,0.1)', marginBottom: '100px', paddingBottom: '60px', background: 'transparent' }}>
                                          <div style={{marginBottom:'30px'}}>
                                              <span style={{fontSize:'2.2rem', color:'#94a3b8', display:'block', marginBottom:'10px'}}>{sem.branch} • Semester {sem.semester}</span>
                                              <h3 style={{fontSize:'4.5rem', color:'#60a5fa', margin:0}}>Section {secLetter}</h3>
                                          </div>
                                          <div style={{width:'100%', overflowX:'auto'}}>
                                              <TimetableGrid role="STUDENT" branch={sem.branch} semester={sem.semester} section={`Sec_${secLetter}`} key={Date.now()} />
                                          </div>
                                      </div>
                                  );
                              })}
                          </div>
                      ))}
                  </div>
              </div>
          </div>
      );
  }

  if (step === 3 && showSuccess) {
      return (
          <div style={pageStyle}>
              <div style={glassContainerStyle}>
                  <div style={{flex:1, display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', textAlign:'center'}}>
                      <div style={{fontSize:'12rem', marginBottom:'40px'}}>🎉</div>
                      <h1 style={{fontSize:'6rem', fontWeight:'900', color:'#4ade80', marginBottom:'30px'}}>Timetable Generated!</h1>
                      <div style={{display:'flex', gap:'50px'}}>
                          <button style={{...largeBtnStyle, background:'#3b82f6', color:'white', padding:'30px 70px', fontSize:'2rem'}} onClick={() => setViewAllMode(true)}>📅 View Master Schedule</button>
                          <button style={{...largeBtnStyle, background:'transparent', border:'3px solid rgba(255,255,255,0.2)', color:'#cbd5f5', padding:'30px 70px', fontSize:'2rem'}} onClick={() => {setShowSuccess(false); localStorage.removeItem('adminSuccess');}}>⚙️ Configure More</button>
                      </div>
                  </div>
              </div>
          </div>
      );
  }

  return (
    <div style={pageStyle}>
      <div style={{display:'flex', justifyContent:'space-between', alignItems:'center', width:'100%', maxWidth:'1800px', marginBottom:'30px'}}>
          <h1 style={{fontSize: '5rem', fontWeight:'900', background: 'linear-gradient(to right, #60a5fa, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'}}>Admin Portal</h1>
          <button style={{...largeBtnStyle, background: 'rgba(255,255,255,0.1)', color: '#cbd5f5'}} onClick={() => navigate('/')}>🏠 Home</button>
      </div>

      <div style={glassContainerStyle}>
          {step === 1 && (
             <div style={{height:'100%', display:'flex', flexDirection:'column'}}>
                <h2 style={{fontSize:'3rem', marginBottom:'40px'}}>Step 1: Academy Configuration</h2>
                <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'60px'}}>
                    <div><label style={{fontSize:'1.8rem', color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Branch</label><select value={branch} onChange={e => setBranch(e.target.value)} style={bigInputStyle}>{branches.map(b=><option key={b} value={b}>{b}</option>)}</select></div>
                    <div><label style={{fontSize:'1.8rem', color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Cycle</label><select value={cycle} onChange={e => setCycle(e.target.value)} style={bigInputStyle}><option value="Odd">Odd (Sem 1,3,5,7)</option><option value="Even">Even (Sem 2,4,6,8)</option></select></div>
                    <div><label style={{fontSize:'1.8rem', color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Semester</label><select value={currentSem} onChange={e => setCurrentSem(parseInt(e.target.value))} style={bigInputStyle}>{semesterOptions.map(s=><option key={s} value={s}>Sem {s}</option>)}</select></div>
                    <div><label style={{fontSize:'1.8rem', color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Sections</label><select value={numSections} onChange={e => setNumSections(parseInt(e.target.value))} style={bigInputStyle}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} Sections</option>)}</select></div>
                </div>
                <div style={{marginTop:'auto', display:'flex', justifyContent:'flex-end'}}><button style={{...largeBtnStyle, background:'#3b82f6', color:'white'}} onClick={() => setStep(2)}>Next Step →</button></div>
             </div>
          )}

          {step === 2 && (
             <div style={{height:'100%', display:'flex', flexDirection:'column', overflow:'hidden'}}>
                <h2 style={{fontSize:'3rem', marginBottom:'30px'}}>Step 2: Curriculum Setup (Sem {currentSem})</h2>
                <div style={{background:'rgba(0,0,0,0.2)', padding:'40px', borderRadius:'30px', marginBottom:'40px'}}>
                    <div style={{display:'grid', gridTemplateColumns:'2fr 1fr 1fr 200px', gap:'35px', alignItems:'end'}}>
                        <div><label style={{color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Subject Name</label><input style={bigInputStyle} value={tempSubName} onChange={e => setTempSubName(e.target.value)} /></div>
                        <div><label style={{color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Type</label><select style={bigInputStyle} value={tempSubType} onChange={e => setTempSubType(e.target.value)}><option value="Lecture">Lecture</option><option value="Lab">Lab</option></select></div>
                        <div><label style={{color:'#cbd5f5', display:'block', marginBottom:'15px'}}>Hours</label><input style={bigInputStyle} type="number" value={tempSubHours} onChange={e => setTempSubHours(e.target.value)}/></div>
                        <button style={{...largeBtnStyle, background:'#10b981', color:'white', height:'78px'}} onClick={handleCreateSubject}>Add</button>
                    </div>
                </div>
                <div style={{flex:1, overflowY:'auto', display:'flex', flexDirection:'column', gap:'30px'}}>
                    {subjects.map((sub, idx) => (
                        <div key={idx} style={{background:'rgba(255,255,255,0.05)', padding:'30px', borderRadius:'25px'}}>
                            <div style={{display:'flex', justifyContent:'space-between', marginBottom:'20px'}}>
                                <strong style={{fontSize:'2.5rem'}}>{sub.name} ({sub.type})</strong>
                                <button onClick={()=>{const u=subjects.filter((_,i)=>i!==idx);setSubjects(u)}} style={{color:'#ef4444', background:'none', border:'none', cursor:'pointer', fontSize:'1.4rem'}}>Remove</button>
                            </div>
                            <div style={{display:'flex', gap:'20px', marginBottom:'20px'}}>{sub.teachers.map((t,i)=>(<span key={i} style={{background:'rgba(0,0,0,0.3)', padding:'10px 20px', borderRadius:'15px'}}>👨‍🏫 {t}</span>))}</div>
                            <div style={{display:'flex', gap:'20px'}}><input id={`t-input-${idx}`} placeholder="Teacher Name" style={{...bigInputStyle, padding:'15px'}} /><button style={{...largeBtnStyle, padding:'15px 30px'}} onClick={()=>handleAddTeacherToSubject(idx)}>+</button></div>
                        </div>
                    ))}
                </div>
                <div style={{marginTop:'40px', display:'flex', justifyContent:'space-between'}}><button style={{...largeBtnStyle, background:'rgba(255,255,255,0.1)'}} onClick={() => setStep(1)}>Back</button><button style={{...largeBtnStyle, background:'#3b82f6', color:'white'}} onClick={handleSaveSemester}>Save Semester</button></div>
             </div>
          )}

          {step === 3 && !showSuccess && (
             <div style={{height:'100%', display:'flex', flexDirection:'column'}}>
                <div style={{display:'flex', justifyContent:'space-between', marginBottom:'40px'}}><h2 style={{fontSize:'3rem'}}>Draft Dashboard</h2><button onClick={handleClearAll} style={{...largeBtnStyle, background:'#ef4444', color:'white', fontSize:'1.4rem'}}>Clear All</button></div>
                <div style={{flex:1, overflowY:'auto', display:'flex', flexDirection:'column', gap:'30px'}}>
                    {allSemesterData.map((sem, idx) => (
                        <div key={idx} style={{background:'rgba(255,255,255,0.05)', padding:'35px', borderRadius:'25px', cursor:'pointer'}} onClick={() => { setEditIndex(idx); setBranch(sem.branch); setCurrentSem(sem.semester); setNumSections(sem.sections); setSubjects(sem.courses); setStep(2); }}>
                            <strong style={{fontSize:'2.5rem'}}>{sem.branch} - Sem {sem.semester}</strong>
                            <p style={{color:'#94a3b8'}}>{sem.sections} Sections • {sem.courses.length} Subjects</p>
                        </div>
                    ))}
                </div>
                <div style={{marginTop:'40px', display:'flex', gap:'30px'}}><button style={{...largeBtnStyle, background:'rgba(255,255,255,0.1)', flex:1}} onClick={() => setStep(1)}>+ Add Semester</button><button style={{...largeBtnStyle, background:'#10b981', color:'white', flex:2, justifyContent:'center'}} onClick={handleGenerate} disabled={isGenerating}>{isGenerating ? "Generating..." : "🚀 Generate All"}</button></div>
             </div>
          )}
      </div>
    </div>
  );
};

export default Admin;